# Request / response service to generate random goals in regions determined by names

int32 n								# Number of goals
string roi_name						# Name of the goals 
---
geometry_msgs/PoseArray goals		# Goals
